### PR TITLE
Available support for symfony/flex

### PR DESCRIPTION
**Pull request by smoked**

### CODE REVIEW

**Comment by saimaz** [comment]
Thanks for the input, but sadly it is not the only thing to release a support for Symfony flex. First of all, ElasticsearchBundle has to support Symfony flex and then all the "bundle" stuff has to be changed to namespaces in the FiltermanagerBundle.

**Comment by smoked** [comment]
Bad news, because I can't install this package to Symfony 3.4 (with flex) I got the error 

```
- Installation request for __root__ dev-develop -> satisfiable by __root__[dev-develop].
- ongr/filter-manager-bundle v2.1.1 requires symfony/symfony ~3.0 -> satisfiable by symfony/symfony[v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
- symfony/symfony v3.4.9 conflicts with __root__[dev-develop].
```

**Comment by smoked** [comment]
By the way, I tested my solution and this installed by the composer without error for Symfony flex project

**Comment by saimaz** [comment]
Yes, it can be installed, but it doesn't mean it will work.

**Comment by saimaz** [comment]
Since you set up, you fork in your project you can test if it works, and maybe fix what is missing. In that case, I would gladly merge and release a patch or new version.

**Comment by smoked** [comment]
Yes, I will test on my project this package, by the way PHPUnit executed without errors

**Comment by smoked** [comment]
I tested it, this package works with ElasticSearchBundle without errors

**Comment by einorler** [comment]
Closing in favor of #260

**Pull request closed without merging**
