### PR TITLE
Added nested implementation in match search

### LINKED ISSUE #172: Handle nested fields
Nested field support can be added like this:

```yaml
project_foo.widget.title:
    class: NestedMatchSearch
    calls:
            - [setRequestField, ['q']]
            - [setField, ['title,my_object.path+variants.title']]
```

```php
/**
 * Improved match search with nested search capability.
 */
class NestedMatchSearch extends MatchSearch
{
    /**
     * {@inheritdoc}
     */
    public function modifySearch(Search $search, FilterState $state = null, SearchRequest $request = null)
    {
        if ($state && $state->isActive()) {
            if (strpos($this->getField(), ',') !== false) {
                $subQuery = new BoolQuery();
                foreach (explode(',', $this->getField()) as $field) {
                    $subQuery->add($this->buildMatchPart($field, $state), 'should');
                }
                $search->addQuery($subQuery, 'must');
            } else {
                $search->addQuery($this->buildMatchPart($this->getField(), $state), 'must');
            }
        }
    }

    /**
     * Build possibly nested match part.
     *
     * @param string      $field
     * @param FilterState $state
     *
     * @return BuilderInterface
     */
    private function buildMatchPart($field, FilterState $state)
    {
        if (false === strpos($field, '+')) {
            return new MatchQuery($field, $state->getValue());
        } else {
            list ($path, $fieldName) = explode('+', $field);

            return new NestedQuery($path, new MatchQuery($fieldName, $state->getValue()));
        }
    }
}
```

Code is from 0.5.10 branch, so feature conflicts exist.

### PR DESCRIPTION
**Pull request by einorler**
My suggestion on the NestedSearch implementation. @tautrimas , could you take a look and check if this implementation would be something you would use? I think its not necessary to introduce a separate filter that does most of the same things that the normal Match filter does, don't you?

closes #172

### CODE REVIEW

**Comment by tautrimas** [comment]
Hey @einorler,

This would work, but not in all cases.

Whole MatchSearch is flawed in such very important case: Try searching two keywords separated by whitespace. Our business expectation was to find **all** queried tokens (words) in any of the fields. This is impossible to configure given current implementation, unless I missed something.

This might be a separate ticket.

Our version with token splitting on PHP side:

```php
class NestedMatchSearch extends MatchSearch
{
    /**
     * {@inheritdoc}
     */
    public function modifySearch(Search $search, FilterState $state = null, SearchRequest $request = null)
    {
        if (!$state || !$state->isActive()) {
            return;
        }

        $words = preg_split('~[\s,]+~', $state->getValue());

        foreach ($words as $word) {
            if (strpos($this->getField(), ',') !== false) {
                $fields = explode(',', $this->getField());
            } else {
                $fields = [$this->getField()];
            }

            $subQuery = new BoolQuery();
            foreach ($fields as $field) {
                $subQuery->add($this->buildMatchPart($field, $word), 'should');
            }
            $search->addQuery($subQuery, 'must');
        }
    }

    /**
     * Build possibly nested match part.
     *
     * @param string $field
     * @param string $word
     *
     * @return BuilderInterface
     */
    private function buildMatchPart($field, $word)
    {
        if (false === strpos($field, '+')) {
            return new MatchQuery($field, $word);
        } else {
            list ($path, $fieldName) = explode('+', $field);

            return new NestedQuery($path, new MatchQuery($fieldName, $word));
        }
    }
}
```

**Comment by einorler** [comment]
Hey, @tautrimas,
Sorry for a late response, but unless I misunderstand something here, than the behavior that you described is default in the elasticsearch match query:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#query-dsl-match-query-boolean
The Match query that is being used acts as a bool query in the elasticsearch by default, that is all words are analyzed. I will update a test, to include a test case with this behaviour.

**Comment by tautrimas** [comment]
Yes, but you cannot list both nested and normal fields in the `"fields"` key in the same match query.

Document:

```
"name": "foo bar"
"addresses.city": "qux" # nested

"name": "foo"
"addresses.city": "bar" # nested

"name": "foo"
"addresses.city": "qux" # nested
```

How to construct a query, that given "foo bar" string, it will find only first 2 documents?

**Comment by einorler** [comment]
Ok, so I did misunderstand it. In that case you're right, but I do believe it should be a separate ticket. @saimaz wdyt?

**Comment by saimaz** [comment]
@einorler, absolutely

**Comment by tautrimas** [comment]
@einorler: yeah, sorry for abstract explanation, but I see all is good now.

**Pull request merged**
