### PR TITLE
Fixed | Cannot load Twig Environment in Twig\PagerExtension

### PR DESCRIPTION
**Pull request by trandangtri**
I approached the latest version of ONGR via DEMO, and the Product List page didn't work properly with the Pagination function. So I fixed it.

### CODE REVIEW

**Comment by trandangtri** [comment]
Related to: https://github.com/ongr-io/RouterBundle/issues/50

**Comment by trandangtri** [comment]
Passed all tests, please help me to review this. Thanks

**Comment by saimaz** [comment]
This is a big change. It's a BC brake for all existing templates.. Lets hold this PR for a bit and investigate the whole filter manager bundle. Then discuss how to do in this particular case.

**Comment by trandangtri** [comment]
Yup, we should. But we don't need to update any existing templates. All should work properly.

I have to update it because Twig removed `initRuntime` function, that's why FMB didn't initialize an environment variable in an inherited method.

See: https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Extension.php#L16

**Comment by mvar** [comment]
@saimaz this is not such a big change. This way to pass environment exists from Twig 0.9.5 (2010-01-20). I does not require to change templates, so it's not even a BC break.

**Comment by saimaz** [comment]
My bad, I've looked in to it too quickly. So looks like all good to merge then?

**Comment by trandangtri** [comment]
Passed all tests and worked properly with the latest of Twig :)

**Pull request merged**
